// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by `graph set typegen --plugin backup`.
// To regenerate, run that command. The pre-commit drift check
// (`graph set typegen --plugin backup --check`) fails CI if this file diverges from the
// live Python schema declarations.
//
// Source schemas:
//   - tools.dashboard.plugins.backup.entrypoints.schemas:BackupConfigV1
//   - tools.dashboard.plugins.backup.entrypoints.schemas:BackupRunV1
//   - tools.dashboard.plugins.backup.entrypoints.schemas:BackupDrillV1

/**
 * backup.config#1
 * Access pattern: singleton (key strategy: fixed:default)
 */
export interface BackupConfigV1 {
  /** Expected cadence of the hourly tier; staleness is judged against this, whoever owns the schedule */
  hourly_interval_minutes?: number;
  /** Hour (local, 0-23) the daily tier is expected */
  daily_hour?: number;
  /** A tier is stale when age(newest successful capture) exceeds this multiple of its expected interval (driver S2: the invariant, never scheduler activity) */
  staleness_multiple?: number;
  /** Capture directories retained on the hourly tier */
  keep_hourly?: number;
  /** Capture directories retained on the daily tier */
  keep_daily?: number;
  /** Scheduled restore-drill cadence; 0 disables scheduled drills (on-demand still works) */
  drill_cadence_days?: number;
  /** A drill running longer is killed and recorded as timeout */
  drill_timeout_minutes?: number;
  /** Whether captures push to the offsite restic repo */
  offsite_enabled?: boolean;
  /** Offsite provider; empty = not configured. Secrets are NOT here — they live in autonomy.vault.audited (backup.restic-password, backup.b2-key-id, backup.b2-application-key) */
  offsite_provider?: '' | 'b2' | 'r2' | 's3';
  /** Offsite bucket/repository name (configuration, not a secret) */
  offsite_bucket?: string;
  /** Who triggers captures on this machine: the host crontab, or the plugin's background loop (stakeholder decision 3, graph://7c45a180-345) */
  schedule_owner?: 'cron' | 'plugin';
  /** backup.run rows kept per tier by the reconciler; Settings must stay bounded */
  run_retention?: number;
  /** backup.drill rows kept */
  drill_retention?: number;
}

/**
 * backup.run#1
 * Access pattern: keyed_per_entity (key strategy: tier:stamp)
 */
export interface BackupRunV1 {
  /** complete = every required store captured; failed = any required store missing or errored (the engine's exit-code contract, never softened here) */
  verdict: 'complete' | 'failed';
  /** ISO-8601 start of the capture */
  started_at: string;
  /** ISO-8601 end of the capture */
  finished_at?: string;
  /** Wall-clock capture duration */
  duration_seconds?: number;
  /** Which engine captured: host cron/bash or the node's rolling mode */
  origin?: 'host' | 'node';
  /** The AUTONOMY_DATA_ROOT the run resolved (the 2026-09-06 incident was exactly this being wrong) */
  data_root?: string;
  /** Where this run wrote its capture — evidence of the actual destination, so the page never guesses */
  backup_root?: string;
  /** Cumulative unique bytes in the offsite restic repository after this run's push (restic stats raw-data); 0 = not measured */
  offsite_repo_bytes?: number;
  /** Per-store outcomes, in capture order */
  stores?: { name: string; action?: string; status: string; bytes?: number; reason?: string }[];
  /** Stores captured (marker's stores= line) */
  store_count?: number;
  /** Dolt databases dumped (marker's beads_databases=) */
  beads_databases?: number;
  /** Sum of captured store bytes */
  total_bytes?: number;
  /** Outcome of the offsite push for this run; skipped = not configured, unknown = report predates the offsite step or the run failed before it */
  offsite?: 'complete' | 'failed' | 'skipped' | 'unknown';
  /** Failure reasons, verbatim from the engine */
  failures?: string[];
  /** Engine exit code: 0 complete, 1 capture failed, 2 capture ok but offsite failed */
  exit_code?: number;
}

/**
 * backup.drill#1
 * Access pattern: keyed_per_entity (key strategy: stamp)
 */
export interface BackupDrillV1 {
  /** running while in flight; pass only when every check is ok; timeout when the subprocess was killed */
  verdict: 'running' | 'pass' | 'fail' | 'timeout';
  /** Operator-initiated or cadence-initiated */
  trigger?: 'manual' | 'scheduled';
  /** ISO-8601 start */
  started_at: string;
  /** ISO-8601 end; empty while running */
  finished_at?: string;
  /** Wall-clock drill duration */
  duration_seconds?: number;
  /** Restic snapshot id the drill restored */
  snapshot_id?: string;
  /** Per-check outcomes with what-was-seen detail */
  checks?: { name: string; status: string; detail?: string }[];
  /** Bounded tail of the drill output (the proof, not the full log) */
  evidence?: string;
}
