// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by `graph set typegen --schemas agents.capabilities.github.schemas:CheckEntryV1,agents.capabilities.github.schemas:ReviewPayloadV1,agents.capabilities.github.schemas:WorktreeGithubExecResultV1,agents.capabilities.github.schemas:ProbeResultV1 --name capability-github`.
// To regenerate, run that command. The pre-commit drift check
// (`graph set typegen --schemas agents.capabilities.github.schemas:CheckEntryV1,agents.capabilities.github.schemas:ReviewPayloadV1,agents.capabilities.github.schemas:WorktreeGithubExecResultV1,agents.capabilities.github.schemas:ProbeResultV1 --name capability-github --check`) fails CI if this file diverges from the
// live Python schema declarations.
//
// Source schemas:
//   - agents.capabilities.github.schemas:CheckEntryV1
//   - agents.capabilities.github.schemas:ReviewPayloadV1
//   - agents.capabilities.github.schemas:WorktreeGithubExecResultV1
//   - agents.capabilities.github.schemas:ProbeResultV1

/**
 * agents.capabilities.github.check_entry#1
 */
export interface CheckEntryV1 {
  /** Stable identifier for the check (gh's id, name, or context) */
  id: string;
  /** 1-2 character glyph derived from the label */
  icon: string;
  /** Operator-facing check name */
  label: string;
  /** Normalized lifecycle state */
  status: 'pass' | 'fail' | 'running' | 'pending';
  /** Optional longer-form failure / progress detail */
  detail?: string;
}

/**
 * agents.capabilities.github.review_payload#1
 */
export interface ReviewPayloadV1 {
  /** GitHub PR number (None for synthesized non-PR branches) */
  number?: number;
  /** GitHub node ID / subscribable ID for PR-level subscription */
  node_id: string;
  /** Canonical web URL of the PR */
  url: string;
  /** PR title */
  title: string;
  /** PR description body */
  body: string;
  /** Head commit SHA of the PR */
  head_sha: string;
  /** Base commit SHA. For a single PR, the merge-base with ``base_branch``. For a stacked PR, the previous PR's head_sha. */
  base_sha: string;
  /** Integration branch name the PR targets */
  base_branch: string;
  /** GitHub PR state */
  state: 'open' | 'closed' | 'merged' | 'unknown';
  /** True when the PR is in draft mode */
  is_draft: boolean;
  /** Aggregate gate state surfaced as the PR badge color */
  aggregate_state: 'green' | 'yellow';
  /** True when at least one check is running or pending */
  running: boolean;
  /** Normalized merge-gate checks for the PR */
  checks: { id: string; icon: string; label: string; status: 'pass' | 'fail' | 'running' | 'pending'; detail?: string }[];
  /** Local SHAs in ``rev-list base..HEAD`` order assigned to this PR (stacked-PR aware) */
  commit_shas: string[];
}

/**
 * agents.capabilities.github.exec_result#1
 */
export interface WorktreeGithubExecResultV1 {
  /** Op name (one of OP_REVIEW_READ / OP_REVIEW_REFRESH / OP_GATES_WATCH_SET) */
  operation: string;
  /** Worktree session id */
  session_name: string;
  /** Worktree repo handle */
  repo_name: string;
  /** True iff ``failure is None`` */
  ok: boolean;
  /** Captured docker-exec stdout */
  stdout: string;
  /** Captured docker-exec stderr */
  stderr: string;
  /** Process exit code (0 on success) */
  exit_code: number;
  /** True when the docker-exec hit the operation timeout */
  timed_out: boolean;
  /** Live container name backing the worktree row */
  container_name?: string;
  /** Branch the operation targeted */
  branch?: string;
  /** ``owner/repo`` slug derived from the managed clone path */
  repo_slug?: string;
  /** Argv passed to ``docker exec`` */
  command: string[];
  /** Canonical failure code (one of FAILURE_*); None on success */
  failure?: string;
  /** Short operator-facing error message; None on success */
  error_message?: string;
}

/**
 * agents.capabilities.github.probe_result#1
 */
export interface ProbeResultV1 {
  /** Capability contract this probe answers for */
  contract: string;
  /** Pinned canonical contract version */
  contract_version: number;
  /** Implementation identifier (e.g. ``autonomy/github``) */
  implementation: string;
  /** Pinned canonical implementation version */
  implementation_version: number;
  /** How the implementation reaches the workspace at launch */
  delivery_mode: 'image_baked' | 'mounted_tools' | 'host_proxy' | 'hybrid';
  /** Probe outcome */
  state: 'ready' | 'unavailable' | 'degraded';
  /** Why the probe is not ``ready`` (one of ``no_live_container`` / ``tool_missing`` / ``env_missing`` / ``probe_failed``); None when ``state == 'ready'`` */
  reason?: string;
  /** Tools the probe expected to find on PATH but did not */
  missing_tools: string[];
  /** Env vars the probe expected to be set but were not */
  missing_env: string[];
  /** Secret files the probe expected to find but did not */
  missing_secret_files: string[];
  /** Free-form diagnostic details. May carry ``exit_code``, ``stderr`` (truncated), and ``timed_out`` for ``probe_failed`` outcomes. */
  details: Record<string, unknown>;
}
