// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by `graph set typegen --plugin coordinator-board`.
// To regenerate, run that command. The pre-commit drift check
// (`graph set typegen --plugin coordinator-board --check`) fails CI if
// this file diverges from the live Python schema declarations.
//
// Source schemas:
//   - tools.dashboard.plugins.coordinator_board.entrypoints.schemas:CoordinatorCanvasV1
//   - tools.dashboard.plugins.coordinator_board.entrypoints.schemas:OperatorMessageToCoordinatorV1
//   - tools.dashboard.plugins.coordinator_board.entrypoints.schemas:CoordinatorTileV1
//   - tools.dashboard.plugins.coordinator_board.entrypoints.schemas:CoordinatorThreadV1
//   - tools.dashboard.plugins.coordinator_board.entrypoints.schemas:CoordinatorDecisionV1

/**
 * dashboard.coordinator-canvas#1
 */
export interface CoordinatorCanvasV1 {
  /** The one well-framed question the coordinator wants the operator to answer right now */
  question: string;
  /** Just-enough context to make the question answerable; supports inline ``[label](href)`` markdown links */
  context?: string;
  /** Age in minutes since the question was published */
  ageMin?: number;
  /** Pre-canned reply suggestions; tapping a pill populates the operator composer verbatim */
  quickReplies?: string[];
}

/**
 * dashboard.operator-message-to-coordinator#1
 */
export interface OperatorMessageToCoordinatorV1 {
  /** Operator's reply body, sent verbatim to the coordinator session */
  text: string;
  /** ISO-8601 send timestamp */
  sentAt?: string;
}

/**
 * dashboard.coordinator-tile#1
 */
export interface CoordinatorTileV1 {
  /** Tile label (peer's working title) */
  label: string;
  /** Peer's session role */
  role: string;
  /** Editorial summary of what the peer is doing */
  thing: string;
  /** What the tile is asking the operator for */
  asks: 'yes_no' | 'decide' | 'merge' | 'approve' | 'fyi';
  /** Age in minutes since the tile last updated */
  ageMin?: number;
  /** Refresh vs discovery update */
  updateKind?: 'refresh' | 'discovery';
  /** Optional longer-form supporting detail (string) */
  detail?: string;
}

/**
 * dashboard.coordinator-thread#1
 */
export interface CoordinatorThreadV1 {
  /** Thread label (working title) */
  label: string;
  /** Session role driving the thread */
  role: string;
  /** Thread status; drives the badge */
  status: 'shipping' | 'blocked' | 'designing' | 'researching' | 'investigating' | 'paused' | 'compacted';
  /** Editorial lead (one-sentence summary) */
  lead: string;
  /** Supporting bullets shown beneath the lead */
  bullets?: string[];
  /** Age in minutes since the thread last updated */
  ageMin?: number;
  /** Total turn count for the thread */
  totalTurns?: number;
  /** When set, the thread is asking the operator for something specific — surfaced as a callout */
  needs?: string;
}

/**
 * dashboard.coordinator-decision#1
 */
export interface CoordinatorDecisionV1 {
  /** Identifier of the tile the operator interacted with (matches a coordinator-tile member's session segment) */
  tile_id: string;
  /** Decision kind; the action handler routes on this field */
  kind: 'thumb_yes' | 'thumb_no' | 'choice' | 'custom' | 'sitrep_request' | 'refresh_request';
  /** Operator's chosen text — the resolution label for ``choice``, the free-text body for ``custom`` */
  choice?: string;
  /** ISO-8601 timestamp of the operator tap */
  sentAt?: string;
  /** Session that should receive the decision via session_send */
  target_session: string;
}
