// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by `graph set typegen --plugin example`.
// To regenerate, run that command. The pre-commit drift check
// (`graph set typegen --plugin example --check`) fails CI if this file diverges from the
// live Python schema declarations.
//
// Source schemas:
//   - tools.dashboard.plugins._example.entrypoints.schemas:ExamplePluginRecordV1

/**
 * dashboard.plugin-example.record#1
 * Access pattern: singleton (key strategy: fixed:current)
 */
export interface ExamplePluginRecordV1 {
  /** Short example message rendered by a plugin client. */
  message: string;
  /** ISO-8601 time at which the example record was written. */
  updated_at: string;
}
