// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by `graph set typegen --plugin fleet`.
// To regenerate, run that command. The pre-commit drift check
// (`graph set typegen --plugin fleet --check`) fails CI if this file diverges from the
// live Python schema declarations.
//
// Source schemas:
//   (no schemas declared)
