// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by `graph set typegen --plugin mission_control`.
// To regenerate, run that command. The pre-commit drift check
// (`graph set typegen --plugin mission_control --check`) fails CI if this file diverges from the
// live Python schema declarations.
//
// Source schemas:
//   - tools.dashboard.plugins.mission_control.entrypoints.schemas:MissionItemV1

/**
 * dashboard.mission.item#1
 * Access pattern: keyed_per_entity (key strategy: surface_id:item_id)
 */
export interface MissionItemV1 {
  /** What the item is; picks the renderer and default section */
  kind: 'scope' | 'work' | 'checkpoint' | 'decision' | 'question' | 'status' | 'metric' | 'incident' | 'exhibit';
  /** Where the item stands, in the platform-wide vocabulary */
  state?: 'proven' | 'done' | 'settled' | 'active' | 'code_only' | 'next' | 'specified' | 'open' | 'blocked' | 'deferred' | 'retired';
  /** Plain-language headline, readable outside the repository */
  title: string;
  /** Supporting prose; plain text, blank line = paragraph break */
  body?: string;
  /** Optional grouping label; blank derives the canonical section from kind */
  section?: string;
  /** Sort key within a section; ties break on title */
  order?: number;
  /** Evidence sentences: what was exercised and what was seen */
  evidence?: string[];
  /** Provenance refs, prefixed: commit:<sha> bead:<id> graph:<id> rev:<n> */
  refs?: string[];
  /** Operator-answerable ask text (question kind, open state); one question, names its options, states the consequence */
  ask?: string;
  /** Decision kind: the fork that was faced */
  fork?: string;
  /** Decision kind: the option taken and why */
  chosen?: string;
  /** Decision kind: what fails if the choice proves wrong */
  if_wrong?: string;
  /** Metric kind: the headline figure, units included */
  value?: string;
  /** Exhibit kind: trusted self-contained HTML fragment; same trust level as a free-form screen push */
  html?: string;
  /** ISO-8601 moment the state was earned in the world, when known; blank falls back to the row's updated_at */
  happened_at?: string;
  /** Owning session or pillar name, for cross-surface rows */
  owner?: string;
}
