// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by `graph set typegen --plugin mission`.
// To regenerate, run that command. The pre-commit drift check
// (`graph set typegen --plugin mission --check`) fails CI if this file diverges from the
// live Python schema declarations.
//
// Source schemas:
//   - tools.dashboard.plugins.mission.entrypoints.schemas:MissionV1
//   - tools.dashboard.plugins.mission.entrypoints.schemas:MissionPillarV1
//   - tools.dashboard.plugins.mission.entrypoints.schemas:MissionContentV1
//   - tools.dashboard.plugins.mission.entrypoints.schemas:MissionChatV1

/**
 * mission.registry#1
 * Access pattern: keyed_per_entity (key strategy: mission_id)
 */
export interface MissionV1 {
  /** Display name, readable outside the repository */
  name: string;
  /** Explicit lifecycle; never inferred from activity */
  status?: 'active' | 'paused' | 'complete';
  /** Session receiving mission-level chat and questions; routing data, not a permission */
  coordinator_session?: string;
  /** ISO-8601 moment of the last lifecycle transition; stamped by the status route, shown beside last activity on the homepage */
  status_changed_at?: string;
}

/**
 * mission.pillar#1
 * Access pattern: keyed_per_entity (key strategy: mission_id:pillar_id)
 */
export interface MissionPillarV1 {
  /** Display name, readable outside the repository */
  name: string;
  /** CSS color hint for the pillar band; no behavior */
  color?: string;
  /** Explicit lifecycle; never inferred from activity */
  status?: 'active' | 'paused' | 'complete';
  /** Session receiving this pillar's chat and questions */
  coordinator_session?: string;
  /** Sort key across the mission's pillars */
  order?: number;
  /** bd pillar labels this pillar owns (e.g. 'pillar:relay-network'); the task bridge maps beads to the pillar through these, so the organic bd vocabulary never needs a mass retag */
  bead_labels?: string[];
}

/**
 * mission.item#1
 * Access pattern: keyed_per_entity (key strategy: mission_id:pillar_id:item_id)
 */
export interface MissionContentV1 {
  /** What the item is; picks renderer, tab, and vocabulary */
  kind: 'scope' | 'status' | 'checkpoint' | 'decision' | 'question';
  /** Per-kind state; empty for stateless kinds (scope, status, decision) */
  state?: '' | 'confirmed' | 'in_progress' | 'pending' | 'open' | 'answered';
  /** Plain-language headline, readable outside the repo */
  title: string;
  /** Supporting prose; markdown subset (headings, lists, fences, links, graph://ids, images -> gallery) */
  body?: string;
  /** Explicit pin within a tab; 0 defers to the tab's own rule (news: newest first; delivery: bead topology) */
  order?: number;
  /** Optional group heading within the item's tab (e.g. a phase name); blank means ungrouped */
  section?: string;
  /** Checkpoint evidence entries, each with provenance */
  evidence?: { text: string; at?: string; by?: string; turn?: number }[];
  /** Provenance refs, prefixed: bead:<id> commit:<sha> graph:<id>; a checkpoint's bead refs are its linked tasks */
  refs?: string[];
  /** Reader-directed ask text (question kind): one answerable question naming options and consequence */
  ask?: string;
  /** Question kind: this open question prevents forward progress (task dependency order is sequencing, never blockage) */
  blocking?: boolean;
  /** Question kind: who asked (session name or label) */
  asked_by?: string;
  /** Question kind: ISO-8601 moment it was asked */
  asked_at?: string;
  /** Question kind: the conversation — attributed replies and progress entries; a reply is NOT an answer */
  discussion?: { by: string; at: string; text: string; type?: string }[];
  /** Question kind: the one cohesive resolution {text, by, at}; filing it closes the question */
  answer?: Record<string, unknown>;
  /** Decision kind: the fork that was faced */
  fork?: string;
  /** Decision kind: the option taken and why */
  chosen?: string;
  /** Decision kind: what fails if the choice proves wrong */
  if_wrong?: string;
  /** Decision kind: pinned as a favorite / FAQ decision */
  faq?: boolean;
  /** Checkpoint kind: attributed progress entries appended while a session works the criterion; 'actively worked' is derived from recency, never stored */
  work?: { by: string; at: string; text: string }[];
  /** Checkpoint kind: every state transition, appended by the state route — the trail the upserting store cannot keep itself */
  history?: { from: string; to: string; at: string; by: string }[];
  /** Checkpoint kind: session that confirmed the demonstration */
  confirmed_by?: string;
  /** Checkpoint kind: turn in the confirming session */
  confirmed_turn?: number;
  /** Checkpoint kind: ISO-8601 moment of confirmation */
  confirmed_at?: string;
  /** ISO-8601 moment the item's fact was earned; blank falls back to the row's updated_at */
  happened_at?: string;
  /** Owning session or pillar name, for cross-surface rows */
  owner?: string;
  /** Withdrawn; kept for the record, hidden from screens */
  retired?: boolean;
}

/**
 * mission.chat#1
 * Access pattern: append_only_log (key strategy: mission_id:pillar_id:uuid)
 */
export interface MissionChatV1 {
  /** Writer: org member persona public key (64 hex; resolved via autonomy.org.member-profile at render) or an agent session name. Superseded by the signed envelope's terminal_persona once signing lands */
  by: string;
  /** ISO-8601 moment the message was sent */
  at: string;
  /** Message prose (markdown subset) */
  text: string;
}
