// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by `graph set typegen --plugin nexus`.
// To regenerate, run that command. The pre-commit drift check
// (`graph set typegen --plugin nexus --check`) fails CI if this file diverges from the
// live Python schema declarations.
//
// Source schemas:
//   - tools.dashboard.plugins.nexus.entrypoints.schemas:NexusSceneV1
//   - tools.dashboard.plugins.nexus.entrypoints.schemas:NexusTileV1

/**
 * dashboard.nexus.scene#1
 * Access pattern: singleton (key strategy: fixed:active)
 */
export interface NexusSceneV1 {
  /** Page banner headline (e.g. 'Settings'). */
  title: string;
  /** Sub-headline beneath the title. */
  subtitle?: string;
  /** One-paragraph anchor quote rendered as the indigo-bordered callout under the banner. */
  anchor_sentence?: string;
  /** Source id of the session driving the scene; surfaced verbatim in the banner's 'Presenter' line. */
  presenter?: string;
  /** Human-readable label for the presenter session. */
  presenter_label?: string;
  /** Optional id of the tile the scene wants to spotlight; the page may render this tile larger or pin it on top. */
  focus_tile_id?: string;
  /** Overall layout hint: ``spotlight`` (focused tile dominates), ``grid`` (equal cards), ``stream`` (vertical journal). */
  layout?: 'spotlight' | 'grid' | 'stream';
}

/**
 * dashboard.nexus.tile#1
 * Access pattern: keyed_per_entity (key strategy: tile_name)
 */
export interface NexusTileV1 {
  /** Sort key; higher orders render first (descending). */
  order?: number;
  /** Width hint for the timeline grid. */
  width?: 'full' | 'half' | 'third';
  /** Discriminator selecting the renderer + the keys consulted from ``data``. */
  kind: 'thinking' | 'quote' | 'code' | 'findings' | 'status' | 'action' | 'link' | 'session-card' | 'merge' | 'phases' | 'markdown' | 'image' | 'table' | 'bead-card' | 'progress';
  /** Optional headline rendered above ``body``. */
  title?: string;
  /** Primary text content. For ``markdown`` kind this is the markdown source; for ``code`` it is the code block. */
  body?: string;
  /** Optional ISO-8601 timestamp surfaced in the meta-row. */
  ts?: string;
  /** Kind-specific payload. The page reads keys it knows about for the matching ``kind`` (e.g. ``state`` + ``label`` + ``detail`` for ``status`` tiles, ``language`` + ``caption`` for ``code`` tiles, etc.). */
  data?: Record<string, unknown>;
}
