// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by `graph set typegen --plugin presentations`.
// To regenerate, run that command. The pre-commit drift check
// (`graph set typegen --plugin presentations --check`) fails CI if this file diverges from the
// live Python schema declarations.
//
// Source schemas:
//   - tools.dashboard.plugins.presentations.entrypoints.schemas:PresentationDeckV1

/**
 * dashboard.presentation.deck#1
 * Access pattern: keyed_per_entity (key strategy: design_id)
 */
export interface PresentationDeckV1 {
  /** Stable Design Studio design id */
  design_id: string;
  /** Deprecated cached revision id; API responses compute the latest revision from design_id */
  latest_revision_id?: string;
  /** Deck display name */
  name: string;
  /** Deck subtitle/description */
  subtitle?: string;
  /** Original design creation timestamp */
  created_at?: string;
  /** Latest Design Studio revision timestamp */
  modified_at?: string;
  /** Most recent presentation timestamp */
  last_shown_at?: string;
  /** Session that created the deck */
  creator_session_id?: string;
  /** Human label for creator session */
  creator_session_label?: string;
  /** Future multi-author owner session */
  author_session_id?: string;
  /** Future multi-author owner label */
  author_session_label?: string;
  /** Number of slides detected by viewer */
  slide_count?: number;
  /** Stable slide ids */
  slide_ids?: string[];
}
