// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by `graph set typegen --plugin testing`.
// To regenerate, run that command. The pre-commit drift check
// (`graph set typegen --plugin testing --check`) fails CI if this file diverges from the
// live Python schema declarations.
//
// Source schemas:
//   - tools.dashboard.plugins.testing.entrypoints.schemas:AgentTestRunV1
//   - tools.dashboard.plugins.testing.entrypoints.schemas:AgentTestObservationV1
//   - tools.dashboard.plugins.testing.entrypoints.schemas:AgentTestTelemetryV1

/**
 * dashboard.testing.run#1
 * Access pattern: keyed_per_entity (key strategy: run_id)
 */
export interface AgentTestRunV1 {
  /** Stable credential-free repository identity. */
  repository: string;
  /** Agent session that requested the run. */
  session: string;
  /** Terminal run status. */
  status: string;
  /** Execution mode: run or collect. */
  mode: string;
  /** Wall time spent executing the run. */
  duration_seconds: number;
  /** ISO-8601 run creation time. */
  created_at: string;
  /** ISO-8601 terminal time. */
  finished_at: string;
  /** Explicit selectors requested for this run. */
  selectors: string[];
  /** Number of test nodes collected. */
  collected: number;
  /** Number of test nodes that passed. */
  passed: number;
  /** Number of call-phase failures. */
  failed: number;
  /** Number of setup or teardown errors. */
  errors: number;
  /** Number of skipped test nodes. */
  skipped: number;
  /** Failures not present in retained baselines. */
  new_failures?: number;
  /** Failures seen in prior retained runs. */
  known_failures?: number;
  /** Failures matching the repository quarantine. */
  quarantined_failures?: number;
  /** Configured pytest worker parallelism. */
  parallelism?: number;
  /** Agent Test version that produced the run. */
  agent_test_version?: string;
  /** Code and selector fingerprint used for repeat refusal. */
  fingerprint?: string;
  /** Prior run whose retained failures selected this run. */
  rerun_of?: string;
  /** History-based estimate shown before launch. */
  estimated_seconds?: number;
  /** Observed low estimate for known tests. */
  estimated_low_seconds?: number;
  /** Observed high estimate for known tests. */
  estimated_high_seconds?: number;
  /** Whether every requested test node had timing history. */
  estimate_complete?: boolean;
  /** Historical test nodes contributing to the estimate. */
  estimate_sampled_tests?: number;
  /** Whether execution exceeded the adaptive no-advancement threshold. */
  hang_detected?: boolean;
  /** Most likely node that stopped advancing, when known. */
  hung_nodeid?: string;
  /** Bounded explanation for a recorded hang suspicion. */
  hang_reason?: string;
  /** Elapsed execution time when hang suspicion was recorded. */
  hang_elapsed_seconds?: number;
  /** Adaptive threshold that triggered hang suspicion. */
  hang_threshold_seconds?: number;
}

/**
 * dashboard.testing.test-observation#1
 * Access pattern: append_only_log (key strategy: uuid_v4)
 */
export interface AgentTestObservationV1 {
  /** Stable credential-free repository identity. */
  repository: string;
  /** Completed Agent Test run that produced this observation. */
  run_id: string;
  /** Fully-qualified pytest node id. */
  nodeid: string;
  /** Setup, call, and teardown time combined. */
  duration_seconds: number;
  /** Terminal outcome for this test node. */
  outcome: string;
  /** Unix timestamp when the observation was recorded. */
  recorded_at: number;
}

/**
 * dashboard.testing.telemetry#1
 * Access pattern: keyed_per_entity (key strategy: session_id)
 */
export interface AgentTestTelemetryV1 {
  /** Cumulative event-name to count mapping. */
  counts: Record<string, unknown>;
  /** Most recent event name. */
  last_event: string;
  /** Unix time of the most recent event. */
  last_at: number;
}
