// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by `graph set typegen --plugin voice_notes`.
// To regenerate, run that command. The pre-commit drift check
// (`graph set typegen --plugin voice_notes --check`) fails CI if this file diverges from the
// live Python schema declarations.
//
// Source schemas:
//   - tools.dashboard.plugins.voice_notes.entrypoints.schemas:VoiceNoteV1

/**
 * dashboard.voice-notes.note#1
 * Access pattern: keyed_per_entity (key strategy: note_id)
 */
export interface VoiceNoteV1 {
  /** Stable note identifier */
  note_id: string;
  /** Human-readable note title */
  title?: string;
  /** Editable note body */
  body?: string;
  /** UTC creation timestamp */
  created_at: string;
  /** UTC last-save timestamp */
  updated_at: string;
}
