#!/usr/bin/env bash
# auto-update-image.sh — daily check for Codex/Claude updates, rebuild image if drift.
#
# Policy:
#   - Codex: bump to the latest stable (no -alpha/-beta/-rc) version whose npm
#     release timestamp is at least 7 days old.
#   - Claude: bake whatever is currently installed on the host. The Claude
#     native installer auto-updates separately; we capture its current state at
#     build time. (We don't gate Claude on a 7-day hold because there is no
#     dry-run on `claude update` to peek at the target version.)
#
# Action: if either drifts from what was last baked, rewrite the Dockerfile
# CODEX_VERSION arg and run agents/build.sh. Log to ~/.cache/autonomy/.
# Notify via graph crosstalk broadcast on actual rebuilds and failures.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
LOG_DIR="$HOME/.cache/autonomy"
LOG_FILE="$LOG_DIR/image-updates.log"
STATE_FILE="$SCRIPT_DIR/.build-state"
LOCK_FILE="/tmp/autonomy-auto-update-image.lock"
HOLD_DAYS="${HOLD_DAYS:-7}"
DRY_RUN="${DRY_RUN:-0}"

mkdir -p "$LOG_DIR"

log() {
    echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*" | tee -a "$LOG_FILE"
}

fail() {
    log "FAIL: $*"
    graph note "auto-update-image FAILED: $*" --tags ops,image-update,failure 2>/dev/null || true
    exit 1
}

# Bail if a previous run is still in flight
exec 9>"$LOCK_FILE"
if ! flock -n 9; then
    log "Skipping — previous run still holding $LOCK_FILE"
    exit 0
fi

log "=== auto-update-image start (HOLD_DAYS=$HOLD_DAYS DRY_RUN=$DRY_RUN) ==="

# ── Resolve eligible Codex version ──
log "Querying npm for @openai/codex release times…"
CODEX_NEW=$(docker run --rm node:20-alpine sh -c "
    npm view @openai/codex time --json 2>/dev/null | \
    node -e \"
        const t = JSON.parse(require('fs').readFileSync(0, 'utf8'));
        const cutoff = new Date(Date.now() - $HOLD_DAYS * 86400_000);
        const stable = Object.entries(t)
            .filter(([v]) => /^[0-9]+\.[0-9]+\.[0-9]+\$/.test(v))
            .filter(([_, ts]) => new Date(ts) <= cutoff)
            .sort((a, b) => new Date(a[1]) - new Date(b[1]));
        if (stable.length === 0) { console.error('no eligible version'); process.exit(1); }
        console.log(stable[stable.length - 1][0]);
    \"
") || fail "could not resolve eligible Codex version"
log "Codex eligible: $CODEX_NEW"

CODEX_CUR=$(grep -oP '^ARG CODEX_VERSION=\K[0-9.]+' "$SCRIPT_DIR/Dockerfile" || true)
log "Codex pinned:   $CODEX_CUR"

# ── Resolve current host Claude ──
CLAUDE_BIN="$(readlink -f "$HOME/.local/bin/claude" 2>/dev/null || true)"
if [[ -z "$CLAUDE_BIN" || ! -x "$CLAUDE_BIN" ]]; then
    fail "host claude not found at ~/.local/bin/claude"
fi
CLAUDE_NEW=$("$CLAUDE_BIN" --version 2>/dev/null | awk '{print $1}')
log "Claude host:    $CLAUDE_NEW"

CLAUDE_LAST=""
if [[ -f "$STATE_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$STATE_FILE"
    CLAUDE_LAST="${LAST_BUILT_CLAUDE:-}"
fi
log "Claude last built: ${CLAUDE_LAST:-<none>}"

# ── Decide ──
NEED_REBUILD=0
REASONS=()
# Never downgrade: the 7-day hold gates UPGRADES only. If the eligible
# (newest ≥HOLD_DAYS-old) version is older than what's already baked — e.g. a
# deliberate manual bump to a newer-than-hold codex — LEAVE it, don't revert.
# (Regression 2026-07-12: a manual 0.144.1 bump for GPT-5.6 got reverted to
# 0.142.5 the next morning because this fired on the downgrade.)
if [[ "$CODEX_NEW" != "$CODEX_CUR" ]] \
   && [[ "$(printf '%s\n%s\n' "$CODEX_CUR" "$CODEX_NEW" | sort -V | tail -1)" == "$CODEX_NEW" ]]; then
    NEED_REBUILD=1
    REASONS+=("codex $CODEX_CUR → $CODEX_NEW")
fi
if [[ "$CLAUDE_NEW" != "$CLAUDE_LAST" ]]; then
    NEED_REBUILD=1
    REASONS+=("claude ${CLAUDE_LAST:-<none>} → $CLAUDE_NEW")
fi

if [[ $NEED_REBUILD -eq 0 ]]; then
    log "No drift — nothing to do"
    exit 0
fi

log "Drift detected: ${REASONS[*]}"

if [[ "$DRY_RUN" == "1" ]]; then
    log "DRY_RUN=1 — would rebuild but skipping"
    exit 0
fi

# ── Apply ──
if [[ "$CODEX_NEW" != "$CODEX_CUR" ]]; then
    log "Bumping CODEX_VERSION in Dockerfile"
    sed -i "s/^ARG CODEX_VERSION=.*/ARG CODEX_VERSION=$CODEX_NEW/" "$SCRIPT_DIR/Dockerfile" || fail "sed bump failed"
fi

log "Running agents/build.sh"
if ! "$SCRIPT_DIR/build.sh" >>"$LOG_FILE" 2>&1; then
    fail "agents/build.sh failed — see $LOG_FILE"
fi

# Persist state
cat > "$STATE_FILE" <<EOF
# auto-generated by auto-update-image.sh
LAST_BUILT_AT='$(date -u +%Y-%m-%dT%H:%M:%SZ)'
LAST_BUILT_CODEX='$CODEX_NEW'
LAST_BUILT_CLAUDE='$CLAUDE_NEW'
EOF

log "Rebuilt successfully: ${REASONS[*]}"
graph note "autonomy-agent image rebuilt: ${REASONS[*]}" --tags ops,image-update 2>/dev/null || true
